<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'zfjSs7v5tKE=');
$cfg_Cs[2]=array(1,1,1,'SFRNTA==');
$cfg_Cs[3]=array(1,1,1,'RElWJkNTUw==');
$cfg_Cs[4]=array(1,1,1,'SmF2YXNjcmlwdC9BamF4');
$cfg_Cs[5]=array(1,1,1,'RHJlYW13ZWF2ZXI=');
$cfg_Cs[6]=array(0,2,1,'1b6zpM28vK8=');
$cfg_Cs[7]=array(0,3,1,'yO28/s/C1Ng=');
$cfg_Cs[8]=array(0,6,1,'yczGt8/6yts=');
$cfg_Cs[9]=array(0,-8,1,'t9bA4NDFz6I=');
$cfg_Cs[10]=array(0,1,1,'1q/DzkNNUw==');
$cfg_Cs[11]=array(0,1,1,'sO/W+s7EtbU=');
?>