<?php
$z[0]=Array("item","",4,92);
$z[0][4]['name']="更新系统缓存";
$z[0][4]['link']="sys_cache_up.php";
$z[0][4]['rank']="sys_ArcBatch";
$z[0][4]['target']="main";
$z[1]=Array("item","",96,194);
$z[1][4]['name']="文档关键词维护";
$z[1][4]['link']="article_keywords_main.php";
$z[1][4]['rank']="sys_Keyword";
$z[1][4]['target']="main";
$z[2]=Array("item","",198,292);
$z[2][4]['name']="数据库内容替换";
$z[2][4]['link']="sys_data_replace.php";
$z[2][4]['rank']="sys_ArcBatch";
$z[2][4]['target']="main";

?>